<ul id="menu">
    <li><a href="<?php echo $this->url(array(), 'stronaglowna') ?>">strona główna</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'ofert', 'action' => 'index', 'module' => 'default'), 'default', true) ?>">twoja oferta</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'setting', 'action' => 'index', 'module' => 'default'), 'default', true) ?>">ustawienia konta</a></li>
    <li><a href="<?php echo $this->url(array('controller' => 'auth', 'action' => 'logout', 'module' => 'default'), 'default', true) ?>">wyloguj</a></li>
</ul>